version: '3'
services:
  mock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: post_hardy_container
    volumes:
      - /home/selo/fisherman/uploads:/home/selo/fisherman/uploads
